<?php
namespace Database\Seeders;

use App\Models\Ebook;
use App\Models\Gender;
use App\Models\Role;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run(){
        $role_data = [
            ['role_id'=>1, 'role_desc'=>'Admin'],
            ['role_id'=>2, 'role_desc'=>'User']
        ]; foreach($role_data as $role){Role::create($role);}
        $gender_data = [
            ['gender_id'=>1, 'gender_desc'=>'Male'],
            ['gender_id'=>2, 'gender_desc'=>'Female']
        ]; foreach($gender_data as $gender){Gender::create($gender);}
        $Ebook_data = [
            ["ebook_id" => 1,"title" =>"The Blue Zones Kitchen: 100 Recipes to Live to 100", "author" => "Dan Buetnerr", "description" => "Building on decades of research, longevity expert Dan Buettner has gathered 100 recipes inspired by the Blue Zones, home to the healthiest and happiest communities in the world. Each dish--for example, Sardinian Herbed Lentil Minestrone; Costa Rican Hearts of Palm Ceviche; Cornmeal Waffles from Loma Linda, California; and Okinawan Sweet Potatoes--uses ingredients and cooking methods proven to increase longevity, wellness, and mental health. Complemented by mouthwatering photography, the recipes also include lifestyle tips (including the best times to eat dinner and proper portion sizes), all gleaned from countries as far away as Japan and as near as Blue Zones project cities in Texas. Innovative, easy to follow, and delicious, these healthy living recipes make the Blue Zones lifestyle even more attainable, thereby improving your health, extending your life, and filling your kitchen with happiness."],
            ["ebook_id" => 2,"title" =>"Ender's Game", "author" => "Orson Scott Card", "description" => "Andrew \"Ender\" Wiggin thinks he is playing computer simulated war games; he is, in fact, engaged in something far more desperate. The result of genetic experimentation, Ender may be the military genius Earth desperately needs in a war against an alien enemy seeking to destroy all human life. The only way to find out is to throw Ender into ever harsher training, to chip away and find the diamond inside, or destroy him utterly. Ender Wiggin is six years old when it begins. He will grow up fast. But Ender is not the only result of the experiment. The war with the Buggers has been raging for a hundred years, and the quest for the perfect general has been underway almost as long. Ender's two older siblings, Peter and Valentine, are every bit as unusual as he is, but in very different ways. While Peter was too uncontrollably violent, Valentine very nearly lacks the capability for violence altogether. Neither was found suitable for the military's purpose. But they are driven by their jealousy of Ender, and by their inbred drive for power. Peter seeks to control the political process, to become a ruler. Valentine's abilities turn more toward the subtle control of the beliefs of commoner and elite alike, through powerfully convincing essays. Hiding their youth and identities behind the anonymity of the computer networks, these two begin working together to shape the destiny of Earth-an Earth that has no future at all if their brother Ender fails."],
            ["ebook_id" => 3,"title" =>"Steve Jobs", "author" => "Walter Isaacson", "description" => "Walter Isaacson's \"enthralling\" (The New Yorker) worldwide bestselling biography of Apple cofounder Steve Jobs. Based on more than forty interviews with Steve Jobs conducted over two years--as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues--Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. Isaacson's portrait touched millions of readers. At a time when America is seeking ways to sustain its innovative edge, Jobs stands as the ultimate icon of inventiveness and applied imagination. He knew that the best way to create value in the twenty-first century was to connect creativity with technology. He built a company where leaps of the imagination were combined with remarkable feats of engineering. Although Jobs cooperated with the author, he asked for no control over what was written. He put nothing off-limits. He encouraged the people he knew to speak honestly. He himself spoke candidly about the people he worked with and competed against. His friends, foes, and colleagues offer an unvarnished view of the passions, perfectionism, obsessions, artistry, devilry, and compulsion for control that shaped his approach to business and the innovative products that resulted. His tale is instructive and cautionary, filled with lessons about innovation, character, leadership, and values. Steve Jobs is the inspiration for the movie of the same name starring Michael Fassbender, Kate Winslet, Seth Rogen, and Jeff Daniels, directed by Danny Boyle with a screenplay by Aaron Sorkin."],
            ["ebook_id" => 4,"title" =>"1776", "author" => "David McCullough", "description" => "In this masterful book, David McCullough tells the intensely human story of those who marched with General George Washington in the year of the Declaration of Independence - when the whole American cause was riding on their success, without which all hope for independence would have been dashed and the noble ideals of the Declaration would have amounted to little more than words on paper. Based on extensive research in both American and British archives, 1776 is a powerful drama written with extraordinary narrative vitality. It is the story of Americans in the ranks, men of every shape, size, and color, farmers, schoolteachers, shoemakers, no-accounts, and mere boys turned soldiers. And it is the story of the King's men, the British commander, William Howe, an his highly disciplined redcoats who looked on their rebel foes with contempt and fought with a valor too little known. At the center of the drama, with Washington, are two young American patriots, who, at first, knew no more of war than what they had read in books - Nathaniel Green, a Quaker who was made a general at thirty-three, and Henry Knox, a twenty-five-year-old bookseller who had the preposterous idea of hauling the guns of Fort Ticonderoga overland to Boston in the dead of Winter. But it is the American commander-in-chief who stands foremost - Washington, who had never before led an army in battle. Written as a companion work to his celebrated biography of John Adams, David McCullough's 1776 is another landmark in the literature of American history."],
            ["ebook_id" => 5,"title" =>"Where the Wild Things Are", "author" => "Maurice Sendak", "description" => "Max, a wild and naughty boy, is sent to bed without his supper by his exhausted mother. In his room, he imagines sailing far away to a land of Wild Things. Instead of eating him, the Wild Things make Max their king."],
            ["ebook_id" => 6,"title" =>"The Subtle Art of Not Giving a Fuck", "author" => "Mark Manson", "description" => "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be \"positive\" all the time so that we can truly become better, happier people. For decades, we’ve been told that positive thinking is the key to a happy, rich life. \"F**k positivity,\" Mark Manson says. \"Let’s be honest, shit is f**ked and we have to live with it.\" In his wildly popular Internet blog, Manson doesn’t sugarcoat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mindset that has infected American society and spoiled a generation, rewarding them with gold medals just for showing up. Manson makes the argument, backed both by academic research and well-timed poop jokes, that improving our lives hinges not on our ability to turn lemons into lemonade, but on learning to stomach lemons better. Human beings are flawed and limited—\"not everybody can be extraordinary, there are winners and losers in society, and some of it is not fair or your fault.\" Manson advises us to get to know our limitations and accept them. Once we embrace our fears, faults, and uncertainties, once we stop running and avoiding and start confronting painful truths, we can begin to find the courage, perseverance, honesty, responsibility, curiosity, and forgiveness we seek. There are only so many things we can give a f**k about so we need to figure out which ones really matter, Manson makes clear. While money is nice, caring about what you do with your life is better, because true wealth is about experience. A much-needed grab-you-by-the-shoulders-and-look-you-in-the-eye moment of real-talk, filled with entertaining stories and profane, ruthless humor, The Subtle Art of Not Giving a F**k is a refreshing slap for a generation to help them lead contented, grounded lives."],
            ["ebook_id" => 7,"title" =>"The Eye of Minds", "author" => "James Dashner", "description" => "Michael is a gamer. And like most gamers, he almost spends more time on the VirtNet than in the actual world. The VirtNet offers total mind and body immersion, and it’s addictive. Thanks to technology, anyone with enough money can experience fantasy worlds, risk their life without the chance of death, or just hang around with Virt-friends. And the more hacking skills you have, the more fun. Why bother following the rules when most of them are dumb, anyway? But some rules were made for a reason. Some technology is too dangerous to fool with. And recent reports claim that one gamer is going beyond what any gamer has done before: he’s holding players hostage inside the VirtNet. The effects are horrific—the hostages have all been declared brain-dead. Yet the gamer’s motives are a mystery. The government knows that to catch a hacker, you need a hacker. And they’ve been watching Michael. They want him on their team. But the risk is enormous. If he accepts their challenge, Michael will need to go off the VirtNet grid. There are back alleys and corners in the system human eyes have never seen and predators he can’t even fathom—and there’s the possibility that the line between game and reality will be blurred forever."],
            ["ebook_id" => 8,"title" =>"Introduction to Linear Algebra", "author" => "Gilbert Strang", "description" => "Linear algebra is something all mathematics undergraduates and many other students, in subjects ranging from engineering to economics, have to learn. The fifth edition of this hugely successful textbook retains all the qualities of earlier editions, while at the same time seeing numerous minor improvements and major additions. The latter include: • A new chapter on singular values and singular vectors, including ways to analyze a matrix of data • A revised chapter on computing in linear algebra, with professional-level algorithms and code that can be downloaded for a variety of languages • A new section on linear algebra and cryptography • A new chapter on linear algebra in probability and statistics. A dedicated and active website also offers solutions to exercises as well as new exercises from many different sources (including practice problems, exams, and development of textbook examples), plus codes in MATLAB®, Julia, and Python."],
            ["ebook_id" => 9,"title" =>"Walking Brooklyn", "author" => "Adrienne Onofri", "description" => "Adrienne Onofri has created an exceptional guide to and through Brooklyn’s most interesting and notable neighborhoods, providing a mix of information about culture, history, architecture, places to eat, venues to visit, and more. From a walk through the Russian-influenced Brighton Beach, to the expansive Prospect Park, and out to Red Hook, Walking Brooklyn reveals the many layers and sites of Manhattan’s lesser-known neighbor. This two-color book features 30 routes, a clear neighborhood map for each walk, black-and-white photographs, and critical public transportation information for every trip. Route summaries make each walk easy to follow, and a “Points of Interest” section outlines each walk’s highlights."],
            ["ebook_id" => 10,"title" =>"Atomic Habits", "author" => "James Clear", "description" => "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights. Clear is known for his ability to distill complex topics into simple behaviors that can be easily applied to daily life and work. Here, he draws on the most proven ideas from biology, psychology, and neuroscience to create an easy-to-understand guide for making good habits inevitable and bad habits impossible. Along the way, readers will be inspired and entertained with true stories from Olympic gold medalists, award-winning artists, business leaders, life-saving physicians, and star comedians who have used the science of small habits to master their craft and vault to the top of their field. Learn how to: make time for new habits (even when life gets crazy); overcome a lack of motivation and willpower; design your environment to make success easier; get back on track when you fall off course; ...and much more. Atomic Habits will reshape the way you think about progress and success, and give you the tools and strategies you need to transform your habits--whether you are a team looking to win a championship, an organization hoping to redefine an industry, or simply an individual who wishes to quit smoking, lose weight, reduce stress, or achieve any other goal."]
        ]; foreach($Ebook_data as $Ebook){Ebook::create($Ebook);}
    }
}
